ws_dir = Pathname.new(__dir__)
ws_dir = ws_dir.parent until
  File.exist?("#{ws_dir}/node_modules/react-native-test-app/test_app.rb") ||
  ws_dir.expand_path.to_s == '/'
require "#{ws_dir}/node_modules/react-native-test-app/test_app.rb"

workspace 'example.xcworkspace'

# Use prebuilt RN.
ENV['RCT_USE_RN_DEP'] = '1'
ENV['RCT_USE_PREBUILT_RNCORE'] = '1'

new_arch_enabled = ENV['NEW_ARCH_ENABLED'].nil? ? true : ENV['NEW_ARCH_ENABLED'] == 'true'

options = {
  :bridgeless_enabled => new_arch_enabled,
  :fabric_enabled =>  new_arch_enabled,
  :hermes_enabled => true,
}

use_test_app! options do |target|
  pod 'stripe-react-native', path: '../node_modules/@stripe/stripe-react-native', testspecs: ['Tests']
  pod 'stripe-react-native/Onramp', path: '../node_modules/@stripe/stripe-react-native'

  # Point Stripe iOS pods to a local checkout for development.
  # Usage: STRIPE_IOS_PATH=~/stripe/stripe-ios pod install --clean-install
  if ENV['STRIPE_IOS_PATH']
    stripe_ios = File.expand_path(ENV['STRIPE_IOS_PATH'])
    pod 'Stripe', path: stripe_ios
    pod 'StripeApplePay', path: stripe_ios
    pod 'StripeCameraCore', path: stripe_ios
    pod 'StripeCore', path: stripe_ios
    pod 'StripeCryptoOnramp', path: stripe_ios
    pod 'StripeFinancialConnections', path: stripe_ios
    pod 'StripeIdentity', path: stripe_ios
    pod 'StripePayments', path: stripe_ios
    pod 'StripePaymentSheet', path: stripe_ios
    pod 'StripePaymentsUI', path: stripe_ios
    pod 'StripeUICore', path: stripe_ios
  end
end
