platform :ios, '11.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'StripeSdkExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
pod 'Stripe', :git => 'https://github.com/stripe/stripe-ios.git', :branch => 'mc-ga-preview-1'
pod 'StripeUICore', :git => 'https://github.com/stripe/stripe-ios.git', :branch => 'mc-ga-preview-1'
pod 'StripeCore', :git => 'https://github.com/stripe/stripe-ios.git', :branch => 'mc-ga-preview-1'


  pod 'stripe-react-native', :path => '../..'
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

  # Workaround for https://github.com/facebook/react-native/issues/30836
  # use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end
