ws_dir = Pathname.new(__dir__)
ws_dir = ws_dir.parent until
  File.exist?("#{ws_dir}/node_modules/react-native-test-app/test_app.rb") ||
  ws_dir.expand_path.to_s == '/'
require "#{ws_dir}/node_modules/react-native-test-app/test_app.rb"
require 'fileutils'

workspace 'example.xcworkspace'
use_frameworks! :linkage => :dynamic

STRIPE_SPM_MODULE_MAP_NAMES = [
  'Stripe',
  'Stripe3DS2',
  'StripeApplePay',
  'StripeCameraCore',
  'StripeCore',
  'StripeCryptoOnramp',
  'StripeFinancialConnections',
  'StripeIdentity',
  'StripeIssuing',
  'StripePaymentSheet',
  'StripePayments',
  'StripePaymentsUI',
  'StripeUICore',
].freeze

def build_setting_values(value)
  return [] if value.nil?
  return value if value.is_a?(Array)

  value.split(' ')
end

def add_spm_build_settings_to_target(target, module_map_names:, additional_swift_flags: [])
  search_paths = [
    '${SYMROOT}/${CONFIGURATION}${EFFECTIVE_PLATFORM_NAME}/',
    '${SYMROOT}/${CONFIGURATION}${EFFECTIVE_PLATFORM_NAME}/PackageFrameworks',
  ]
  framework_search_path = '${SYMROOT}/${CONFIGURATION}${EFFECTIVE_PLATFORM_NAME}/PackageFrameworks'
  module_map_dir = '$(OBJROOT)/GeneratedModuleMaps$(EFFECTIVE_PLATFORM_NAME)'

  target.build_configurations.each do |config|
    [target.build_settings(config.name), config.build_settings].each do |build_settings|
      swift_include_paths = build_setting_values(build_settings['SWIFT_INCLUDE_PATHS'])
      swift_include_paths << '$(inherited)' if swift_include_paths.empty?
      search_paths.each do |search_path|
        swift_include_paths << search_path unless swift_include_paths.include?(search_path)
      end
      build_settings['SWIFT_INCLUDE_PATHS'] = swift_include_paths

      framework_search_paths = build_setting_values(build_settings['FRAMEWORK_SEARCH_PATHS'])
      framework_search_paths << '$(inherited)' if framework_search_paths.empty?
      framework_search_paths << framework_search_path unless framework_search_paths.include?(framework_search_path)
      build_settings['FRAMEWORK_SEARCH_PATHS'] = framework_search_paths

      other_swift_flags = build_setting_values(build_settings['OTHER_SWIFT_FLAGS'])
      other_swift_flags << '$(inherited)' if other_swift_flags.empty?
      additional_swift_flags.each do |flag|
        other_swift_flags << flag unless other_swift_flags.include?(flag)
      end
      module_map_names.each do |name|
        module_map_flag = "-fmodule-map-file=#{module_map_dir}/#{name}.modulemap"
        next if other_swift_flags.include?(module_map_flag)

        other_swift_flags << '-Xcc'
        other_swift_flags << module_map_flag
      end
      build_settings['OTHER_SWIFT_FLAGS'] = other_swift_flags
    end
  end
end

def add_spm_build_settings_to_xcconfig(path, module_map_names:, swift_flags: [])
  return unless File.exist?(path)

  search_paths = [
    '${SYMROOT}/${CONFIGURATION}${EFFECTIVE_PLATFORM_NAME}/',
    '${SYMROOT}/${CONFIGURATION}${EFFECTIVE_PLATFORM_NAME}/PackageFrameworks',
  ]
  framework_search_path = '${SYMROOT}/${CONFIGURATION}${EFFECTIVE_PLATFORM_NAME}/PackageFrameworks'
  module_map_dir = '$(OBJROOT)/GeneratedModuleMaps$(EFFECTIVE_PLATFORM_NAME)'
  swift_flags = [
    *swift_flags,
    *module_map_names.map do |name|
    "-Xcc -fmodule-map-file=#{module_map_dir}/#{name}.modulemap"
    end,
  ]

  lines = File.readlines(path, chomp: true)
  setting_values = {
    'SWIFT_INCLUDE_PATHS' => ['$(inherited)', *search_paths],
    'FRAMEWORK_SEARCH_PATHS' => ['$(inherited)', framework_search_path],
  }
  setting_values['OTHER_SWIFT_FLAGS'] = ['$(inherited)', *swift_flags] unless swift_flags.empty?

  setting_values.each do |setting, values|
    line_index = lines.index { |line| line.start_with?("#{setting} =") }
    existing_values = line_index.nil? ? [] : lines[line_index].split(' = ', 2).last.split(' ')
    values.each do |value|
      existing_values << value unless existing_values.include?(value)
    end

    line = "#{setting} = #{existing_values.join(' ')}"
    if line_index.nil?
      lines << line
    else
      lines[line_index] = line
    end
  end

  File.write(path, "#{lines.join("\n")}\n")
end

def add_spm_build_settings_to_target_support_files(installer, target_name:, xcconfig_names:, module_map_names:, swift_flags: [])
  target_support_dir = installer.sandbox.root + "Target Support Files/#{target_name}"
  xcconfig_names.each do |xcconfig_name|
    add_spm_build_settings_to_xcconfig(
      target_support_dir + xcconfig_name,
      module_map_names: module_map_names,
      swift_flags: swift_flags
    )
  end
end

def set_xcconfig_build_setting(path, setting, value)
  return unless File.exist?(path)

  lines = File.readlines(path, chomp: true)
  line_index = lines.index { |line| line.start_with?("#{setting} =") }
  setting_line = "#{setting} = #{value}"
  if line_index
    lines[line_index] = setting_line
  else
    lines << setting_line
  end
  File.write(path, "#{lines.join("\n")}\n")
end

def allow_non_modular_includes_for_target(installer, target_name)
  target = installer.pods_project.targets.find { |project_target| project_target.name == target_name }
  target&.build_configurations&.each do |config|
    config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end

  target_support_dir = installer.sandbox.root + "Target Support Files/#{target_name}"
  [
    "#{target_name}.debug.xcconfig",
    "#{target_name}.release.xcconfig",
  ].each do |xcconfig_name|
    set_xcconfig_build_setting(
      target_support_dir + xcconfig_name,
      'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES',
      'YES'
    )
  end
end

def add_framework_link_flags_to_xcconfig(path, framework_names:)
  return unless File.exist?(path)

  lines = File.readlines(path, chomp: true)
  line_index = lines.index { |line| line.start_with?('OTHER_LDFLAGS =') }
  existing_values = line_index.nil? ? ['$(inherited)'] : lines[line_index].split(' = ', 2).last.split(' ')
  framework_names.each do |framework_name|
    quoted_framework_name = "\"#{framework_name}\""
    next if existing_values.include?(quoted_framework_name)

    existing_values << '-framework'
    existing_values << quoted_framework_name
  end

  line = "OTHER_LDFLAGS = #{existing_values.join(' ')}"
  if line_index.nil?
    lines << line
  else
    lines[line_index] = line
  end

  File.write(path, "#{lines.join("\n")}\n")
end

def add_framework_link_flags_to_target_support_files(installer, target_name:, framework_names:)
  target_support_dir = installer.sandbox.root + "Target Support Files/#{target_name}"
  Dir.glob("#{target_support_dir}/*.xcconfig").each do |xcconfig|
    add_framework_link_flags_to_xcconfig(xcconfig, framework_names: framework_names)
  end
end

def add_ios_unit_tests_to_app_target(project_path:, target_name:, tests_path:, module_map_names:, swift_flags:)
  project = Xcodeproj::Project.open(project_path)
  target = project.targets.find { |project_target| project_target.name == target_name }
  app_target = project.targets.find { |project_target| project_target.name == 'ReactTestApp' }
  return if target.nil?

  target.build_configurations.each do |config|
    config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    if app_target
      config.build_settings['BUNDLE_LOADER'] = '$(TEST_HOST)'
      config.build_settings['TEST_HOST'] = '$(BUILT_PRODUCTS_DIR)/ReactTestApp.app/ReactTestApp'
    end
    config.build_settings.delete('ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES')
  end
  app_target&.build_configurations&.each do |config|
    config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
  target.add_dependency(app_target) if app_target && target.dependency_for_target(app_target).nil?
  add_spm_build_settings_to_target(target, module_map_names: module_map_names, additional_swift_flags: swift_flags)

  project_dir = Pathname.new(project_path).dirname
  tests_group = project.main_group['StripeReactNativeTests'] ||
                project.main_group.new_group('StripeReactNativeTests')

  Dir.glob("#{tests_path}/*.swift").sort.each do |test_file|
    relative_path = Pathname.new(test_file).relative_path_from(project_dir).to_s
    file_ref = tests_group.files.find { |file| file.path == relative_path } ||
               tests_group.new_file(relative_path)

    next if target.source_build_phase.files_references.include?(file_ref)

    target.source_build_phase.add_file_reference(file_ref)
  end

  project.save

  scheme_dir = File.join(project_path, 'xcshareddata/xcschemes')
  FileUtils.mkdir_p(scheme_dir)
  app_build_action_entry = ''
  app_launch_action_runnable = ''
  if app_target
    app_build_action_entry = <<~XML
               <BuildActionEntry
                  buildForTesting = "YES"
                  buildForRunning = "YES"
                  buildForProfiling = "YES"
                  buildForArchiving = "YES"
                  buildForAnalyzing = "YES">
                  <BuildableReference
                     BuildableIdentifier = "primary"
                     BlueprintIdentifier = "#{app_target.uuid}"
                     BuildableName = "#{app_target.product_reference.path}"
                     BlueprintName = "#{app_target.name}"
                     ReferencedContainer = "container:ReactTestApp.xcodeproj">
                  </BuildableReference>
               </BuildActionEntry>
    XML
    app_launch_action_runnable = <<~XML
            <BuildableProductRunnable
               runnableDebuggingMode = "0">
               <BuildableReference
                  BuildableIdentifier = "primary"
                  BlueprintIdentifier = "#{app_target.uuid}"
                  BuildableName = "#{app_target.product_reference.path}"
                  BlueprintName = "#{app_target.name}"
                  ReferencedContainer = "container:ReactTestApp.xcodeproj">
               </BuildableReference>
            </BuildableProductRunnable>
    XML
  end
  File.write(
    File.join(scheme_dir, "#{target_name}.xcscheme"),
    <<~XML
      <?xml version="1.0" encoding="UTF-8"?>
      <Scheme
         LastUpgradeVersion = "1340"
         version = "1.3">
         <BuildAction
            parallelizeBuildables = "YES"
            buildImplicitDependencies = "YES">
            <BuildActionEntries>
      #{app_build_action_entry.rstrip}
               <BuildActionEntry
                  buildForTesting = "YES"
                  buildForRunning = "NO"
                  buildForProfiling = "NO"
                  buildForArchiving = "NO"
                  buildForAnalyzing = "YES">
                  <BuildableReference
                     BuildableIdentifier = "primary"
                     BlueprintIdentifier = "#{target.uuid}"
                     BuildableName = "#{target.product_reference.path}"
                     BlueprintName = "#{target.name}"
                     ReferencedContainer = "container:ReactTestApp.xcodeproj">
                  </BuildableReference>
               </BuildActionEntry>
            </BuildActionEntries>
         </BuildAction>
         <TestAction
            buildConfiguration = "Debug"
            selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
            selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
            shouldUseLaunchSchemeArgsEnv = "YES">
            <Testables>
               <TestableReference
                  skipped = "NO">
                  <BuildableReference
                     BuildableIdentifier = "primary"
                     BlueprintIdentifier = "#{target.uuid}"
                     BuildableName = "#{target.product_reference.path}"
                     BlueprintName = "#{target.name}"
                     ReferencedContainer = "container:ReactTestApp.xcodeproj">
                  </BuildableReference>
               </TestableReference>
            </Testables>
         </TestAction>
         <LaunchAction
            buildConfiguration = "Debug"
            selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
            selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
            launchStyle = "0"
            useCustomWorkingDirectory = "NO"
            ignoresPersistentStateOnLaunch = "NO"
            debugDocumentVersioning = "YES"
            debugServiceExtension = "internal"
            allowLocationSimulation = "YES">
      #{app_launch_action_runnable.rstrip}
         </LaunchAction>
         <ProfileAction
            buildConfiguration = "Release"
            shouldUseLaunchSchemeArgsEnv = "YES"
            savedToolIdentifier = ""
            useCustomWorkingDirectory = "NO"
            debugDocumentVersioning = "YES">
      #{app_launch_action_runnable.rstrip}
         </ProfileAction>
         <AnalyzeAction
            buildConfiguration = "Debug">
         </AnalyzeAction>
         <ArchiveAction
            buildConfiguration = "Release"
            revealArchiveInOrganizer = "YES">
         </ArchiveAction>
      </Scheme>
    XML
  )
end

# Use prebuilt RN.
ENV['RCT_USE_RN_DEP'] = '1'
ENV['RCT_USE_PREBUILT_RNCORE'] = '1'

new_arch_enabled = ENV['NEW_ARCH_ENABLED'].nil? ? true : ENV['NEW_ARCH_ENABLED'] == 'true'

options = {
  :bridgeless_enabled => new_arch_enabled,
  :fabric_enabled =>  new_arch_enabled,
  :hermes_enabled => true,
  :post_install => lambda do |installer|
    allow_non_modular_includes_for_target(installer, 'ReactNativeHost')
    stripe_react_native_target = installer.pods_project.targets.find { |target| target.name == 'stripe-react-native' }
    add_spm_build_settings_to_target(stripe_react_native_target, module_map_names: []) unless stripe_react_native_target.nil?
    add_spm_build_settings_to_target_support_files(
      installer,
      target_name: 'stripe-react-native',
      xcconfig_names: [
        'stripe-react-native.debug.xcconfig',
        'stripe-react-native.release.xcconfig',
      ],
      module_map_names: []
    )
    add_spm_build_settings_to_target_support_files(
      installer,
      target_name: 'Pods-ReactTestApp-ReactTestAppTests',
      xcconfig_names: [
        'Pods-ReactTestApp-ReactTestAppTests.debug.xcconfig',
        'Pods-ReactTestApp-ReactTestAppTests.release.xcconfig',
      ],
      module_map_names: STRIPE_SPM_MODULE_MAP_NAMES,
      swift_flags: new_arch_enabled ? ['-DRCT_NEW_ARCH_ENABLED'] : []
    )
    add_framework_link_flags_to_target_support_files(
      installer,
      target_name: 'ReactTestApp-DevSupport',
      framework_names: [
        'React',
        'ReactNativeDependencies',
        'hermes',
      ]
    )
    [
      'react-native-safe-area-context',
      'RNCAsyncStorage',
      'RNCPicker',
      'stripe-react-native',
    ].each do |target_name|
      add_framework_link_flags_to_target_support_files(
        installer,
        target_name: target_name,
        framework_names: [
          'React',
        ]
      )
    end
  end,
}

use_test_app! options do |target|
  pod 'stripe-react-native', path: '../node_modules/@stripe/stripe-react-native'
  pod 'stripe-react-native/Onramp', path: '../node_modules/@stripe/stripe-react-native'

  target.tests
end

post_integrate do |_installer|
  add_ios_unit_tests_to_app_target(
    project_path: File.join(ws_dir, 'node_modules/.generated/ios/ReactTestApp.xcodeproj'),
    target_name: 'ReactTestAppTests',
    tests_path: File.join(ws_dir.parent, 'ios/Tests'),
    module_map_names: STRIPE_SPM_MODULE_MAP_NAMES,
    swift_flags: new_arch_enabled ? ['-DRCT_NEW_ARCH_ENABLED'] : []
  )
end
