#!/bin/bash

trap 'exit' INT

PLATFORM=${1:-}

# Validate passed platform
case $PLATFORM in
  ios | android )
    ;;

  *)
    echo "Error! You must pass either 'android' or 'ios'"
    echo ""
    exit 1
    ;;
esac

if [ "$PLATFORM" == "ios" ]; then
  APPID="com.stripe.react.native"
else
  APPID="com.example.reactnativestripesdk"
fi

allTestFiles=$(ls ./e2e-tests/*.yml)
failedTests=()
for file in $allTestFiles
do
  if ! maestro test "$file" -e APP_ID="$APPID";
  then
    failedTests+=("$file")
  fi
done

if [ ${#failedTests[@]} -eq 0 ]; then
    exit 0
else
    echo "These tests failed:"
    printf '%s\n' "${failedTests[@]}"
    exit 1
fi
