// Generated by scripts/generate-package-info.js. Do not edit.
export const packageInfo = {
  name: '@stripe/stripe-react-native',
  url: 'https://github.com/stripe/stripe-react-native',
  version: '0.78.0',
} as const;
