name: RN Stripe

on: push

jobs:
  test:
    name: Install Appium dependencies
    runs-on: macOS-latest
    env:
      API_URL: https://rigorous-heartbreaking-cephalopod.glitch.me
    steps:
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.4.0
      - name: Install React Native CLI
        run: |
          npm install react-native-cli
      - name: Install Repo and Dependencies
        run: |
          yarn bootstrap
      - name: Build iOS App
        run: |
          yarn run-example-ios
          BUILT_APP=`find ~/Library/Developer/Xcode/DerivedData -name StripeSdkExample.app | grep Build/Products/Release-iphonesimulator/StripeSdkExample.app`
          mkdir -p example/ios/DerivedData/StripeSdkExample/Build/Products/Release-iphonesimulator
          cp -R $BUILT_APP example/ios/DerivedData/StripeSdkExample/Build/Products/Release-iphonesimulator
          sleep 30
      - name: Run Tests
        run: |
          node ./run-appium-tests.js ios
      - name: Upload Screenshoots
        uses: actions/upload-artifact@v1
        with:
          name: e2e-results
          path: tmp
      - uses: actions/download-artifact@v2
        with:
          name: e2e-results
          path: tmp
