name: Generate docs

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  generate-docs:
    name: generate-docs
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Node.js environment
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: '.node-version'

      - name: Install Dependencies
        run: |
          yarn example && yarn

      - name: Build docs
        run: yarn docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
        with:
          github_token: ${{ secrets.DOCS_GITHUB_SECRET }}
          publish_dir: ./docs
          commit_message: 'docs: update'
          force_orphan: true
